version: '3.7'

services:
  web:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    expose:
      - "8019"
    ports:
      - 8019:8888
    volumes:
      - ./warrant-lite/:/code/warrant-lite
    env_file: .env
    working_dir: /code/
    command: poetry run jupyter notebook --port=8888 --ip=0.0.0.0 --allow-root
